export const SETTINGS = {
    GROQ_API_KEY: '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',
    API_FOOTBALL_KEY: '6b653386f3a3cb5592e98f59d3521b12',
    CURRENT_SEASON: new Date().getFullYear(),
    CACHE_TTL: 30 * 60 * 1000,
    CREATOR_NUMBER: '5511927018683',
    CREATOR_JID: '5511927018683@s.whatsapp.net',
    CREATOR_NAME: 'Leandro'
};

export const SIGNS = [
    { id: 1, name: 'Áries', emoji: '♈', dates: '21/03 - 20/04' },
    { id: 2, name: 'Touro', emoji: '♉', dates: '21/04 - 20/05' },
    { id: 3, name: 'Gêmeos', emoji: '♊', dates: '21/05 - 20/06' },
    { id: 4, name: 'Câncer', emoji: '♋', dates: '21/06 - 22/07' },
    { id: 5, name: 'Leão', emoji: '♌', dates: '23/07 - 22/08' },
    { id: 6, name: 'Virgem', emoji: '♍', dates: '23/08 - 22/09' },
    { id: 7, name: 'Libra', emoji: '♎', dates: '23/09 - 22/10' },
    { id: 8, name: 'Escorpião', emoji: '♏', dates: '23/10 - 21/11' },
    { id: 9, name: 'Sagitário', emoji: '♐', dates: '22/11 - 21/12' },
    { id: 10, name: 'Capricórnio', emoji: '♑', dates: '22/12 - 20/01' },
    { id: 11, name: 'Aquário', emoji: '♒', dates: '21/01 - 18/02' },
    { id: 12, name: 'Peixes', emoji: '♓', dates: '19/02 - 20/03' }
];

export const FOOTBALL_CHAMPIONSHIPS: Record<string, { name: string, id: number }> = {
    '1': { name: 'Campeonato Brasileiro Série A', id: 71 },
    '2': { name: 'Copa do Brasil', id: 73 },
    '3': { name: 'Libertadores', id: 13 },
    '4': { name: 'Campeonato Paulista', id: 79 }, 
    '5': { name: 'Champions League', id: 2 } 
};

export const NEWS_TOPICS: Record<string, { name: string, query: string }> = {
    '1': { name: 'Economia', query: 'Economia OR Negócios OR Mercado Financeiro' },
    '2': { name: 'Política', query: 'Política' },
    '3': { name: 'Famosos & Celebridades', query: 'Famosos OR Celebridades OR Entretenimento' },
    '4': { name: 'Saúde', query: 'Saúde OR Medicina OR Bem estar' },
    '5': { name: 'Culinária', query: 'Culinária OR Gastronomia OR Receitas' },
    '6': { name: 'Cotidiano', query: 'Cotidiano OR Dia a dia' },
    '7': { name: 'Sociedade', query: 'Sociedade OR Direitos OR Cultura' },
    '8': { name: 'Casa e Bem Estar', query: 'Casa OR Bem estar OR Qualidade de vida' },
    '9': { name: 'Tecnologias', query: 'Tecnologia OR Inovação OR Ciência' }
};

export const QUIZ_DATABASE = [
    { question: 'Qual o maior planeta do Sistema Solar?', answer: 'júpiter' },
    { question: 'Qual o país com a maior população do mundo?', answer: 'índia' },
    { question: 'Qual elemento químico tem o símbolo Au?', answer: 'ouro' },
    { question: 'Qual é a capital da Austrália?', answer: 'canberra' },
    { question: 'Quem pintou a obra Monalisa?', answer: 'Leonardo da Vinci' },
    { question: 'Qual o metal mais abundante na crosta terrestre?', answer: 'alumínio' },
    { question: 'O que tem chave mas não abre portas, tem espaço mas não tem sala, e você pode entrar mas não pode sair?', answer: 'teclado' },
    { question: 'Qual é o oceano mais profundo do planeta Terra?', answer: 'pacífico' },
    { question: 'Quantos ossos tem o corpo humano adulto?', answer: '206' },
    { question: 'Em que ano o homem pisou na Lua pela primeira vez?', answer: '1969' }
];

export const FEATURE_MAP: Record<string, string> = {
    '!bot': 'bot_master',
    '!jarvis': 'jarvis',
    '!ia': 'jarvis',
    '!divulga': 'divulga',
    '!divulgar': 'divulga',
    '!s': 'figurinha',
    '!sticker': 'figurinha',
    '!figurinha': 'figurinha',
    '!s2img': 's2img',
    '!fig': 's2img',
    '!baixarfig': 's2img',
    '!meme': 'meme',
    '!troll': 'troll',
    '!sorteio': 'sorteio',
    '!quiz': 'quiz',
    '!charada': 'quiz',
    '!wiki': 'wiki',
    '!wikipedia': 'wiki',
    '!moeda': 'moeda',
    '!cotacao': 'moeda',
    '!qrcode': 'qrcode',
    '!rank': 'rank',
    '!top': 'rank',
    '!n': 'noticias',
    '!h': 'horoscopo',
    '!t': 'clima',
    '!f': 'futebol',
    '!regras': 'regras',
    '!m': 'metricas',
    '!r': 'resumo',
    '!warn': 'warn',
    '!advertir': 'warn',
    '!warns': 'warn',
    '!advertencias': 'warn',
    '!unwarn': 'warn',
    '!inativos': 'inativos',
    '!fantasmas': 'inativos',
    '!antilink': 'antilink',
    '!antifake': 'antifake',
    '!ddi': 'antifake',
    '!antiflood': 'antiflood',
    '!antighost': 'antighost',
    '!apresentacao': 'antighost',
    '!megafone': 'megafone',
    '!alerta': 'alerta',
    '!auto': 'auto',
    '!sa': 'sa',
    '!exit': 'exit',
    '!saida': 'exit',
    '!bv': 'bv',
    '!ma': 'ma',
    '!fechar': 'fechar_abrir',
    '!abrir': 'fechar_abrir',
    '!ban': 'ban',
    '!kick': 'ban',
    '!admins': 'admins',
    '!adms': 'admins'
};

export const FEATURE_NAMES: Record<string, string> = {
    bot_master: '🔌 Bot Master Geral (!bot on/off)',
    jarvis: '🤖 Jarvis Autônomo & Memória 30min (!jarvis on/off)',
    divulga: '📢 Divulgações Programadas & Links Liberados (!divulga)',
    meme: '😂 Memes Automáticos a cada 2h (!meme)',
    troll: '🎭 Sistema de Trolagem com IA (!troll)',
    figurinha: '🎨 Criador de Figurinhas (!s / !figurinha)',
    s2img: '🖼️ Figurinha para Imagem (!s2img / !fig)',
    sorteio: '🎲 Sorteio no Grupo (!sorteio)',
    quiz: '🧩 Quiz & Charadas (!quiz / !charada)',
    wiki: '📚 Pesquisa Wikipédia (!wiki)',
    moeda: '💵 Cotação de Moedas (!moeda)',
    qrcode: '📱 Gerador de QR Code (!qrcode)',
    rank: '🏆 Ranking de Mensagens (!rank / !top)',
    noticias: '📰 Notícias em Tempo Real (!n)',
    horoscopo: '✨ Horóscopo dos Signos (!h)',
    clima: '🌤️ Previsão do Clima (!t)',
    futebol: '⚽ Futebol ao Vivo (!f)',
    regras: '📋 Consulta e Regras (!regras)',
    metricas: '📊 Métricas de Tráfego (!m)',
    resumo: '📝 Resumo por IA (!r)',
    warn: '⚠️ Sistema de Advertências (!warn / !unwarn)',
    inativos: '👻 Detecção de Inativos (!inativos)',
    antilink: '🛡️ Anti-Link Ban Imediato (!antilink)',
    antifake: '🇧🇷 Filtro DDI +55 / Anti-Fake (!antifake)',
    antiflood: '⚡ Proteção Anti-Flood / Spam (!antiflood)',
    antighost: '👻 Anti-Ghost (Apresentação em 10min) (!antighost)',
    megafone: '📢 Megafone com Trancamento (!megafone)',
    alerta: '🚨 Filtro de Palavras Proibidas (!alerta)',
    auto: '✨ Animação por Inatividade (!auto)',
    sa: '👋 Saudação para Novos Membros (!sa)',
    exit: '👋 Mensagem de Despedida (!exit)',
    bv: '🔔 Lembrete de Boas-Vindas 15min (!bv)',
    ma: '⏰ Mensagens Automáticas (!ma)',
    fechar_abrir: '🔒 Trancar/Abrir Grupo & Horários (!fechar / !abrir)',
    ban: '🚫 Remoção de Membros (!ban / !kick)',
    admins: '🛡️ Identificação de Administradores (!admins)'
};
